workspace:
  base: /workspace
  path: src/github.com/weiwei04/compass

clone:
  compass.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    depth: 1

pipeline:
    build:
      image: alexwei/golang-glide:1.8.3-cs-proxy
      commands:
      - glide install
      - go test -cover $(go list ./... | grep -v /vendor/)
