apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    ke-app: appstore
    ke-svc: helm-registry
  name: helm-registry
  namespace: kube-system
spec:
  rules:
  - host: helm-registry.ke-cs.dev.qiniu.io
    http:
      paths:
      - backend:
          serviceName: helm-registry
          servicePort: 8099
        path: /
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ke-app: appstore
    ke-svc: helm-registry
  name: helm-registry
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8099
  selector:
    ke-app: appstore
    ke-svc: helm-registry
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    ke-app: appstore
    ke-svc: helm-registry
  name: helm-registry
  namespace: kube-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ke-app: appstore
      ke-svc: helm-registry
  serviceName: helm-registry
  template:
    metadata:
      creationTimestamp: null
      labels:
        ke-app: appstore
        ke-svc: helm-registry
    spec:
      containers:
      - image: alexwei/helm-registry:0.1.0
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 8099
          name: registry
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
      storageClassName: ceph-rbd
