apiVersion: v1
kind: Service
metadata:
  labels:
    ke-app: helm-registry
    ke-svc: helm-registry
  name: helm-registry-node-port
  namespace: kube-system
spec:
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 8099
    nodePort: 32588
  selector:
    ke-app: helm-registry
    ke-svc: helm-registry
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
