apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm
    name: tiller
  name: compass-node-port
  namespace: kube-system
spec:
  ports:
  - port: 44134
    protocol: TCP
    targetPort: 44134
    nodePort: 32589
  selector:
    app: helm
    name: tiller
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
