apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    ke-app: helm-registry
    ke-svc: helm-registry
  name: helm-registry
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      ke-app: helm-registry
      ke-svc: helm-registry
      #serviceName: helm-registry
  template:
    metadata:
      creationTimestamp: null
      labels:
        ke-app: helm-registry
        ke-svc: helm-registry
    spec:
      containers:
      - image: alexwei/helm-registry:0.1.0
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 8099
          name: registry
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
